### ISSUE TITLE
Buggy crate tarball due to case-insensitivity 

### ISSUE THREAD

**Issue by kornelski** [mstange/symsrv#10]
`readme = "README.md"` doesn't match `Readme.md` file name, which makes Cargo package both `Readme.md` and `README.md`, creating a buggy tar file.

**Comment by mstange** [comment]
Oh no - I think I've made this mistake before even. Will fix.

**Comment by mstange** [comment]
Released 0.5.2 with hopefully a non-buggy tar file.
