### ISSUE TITLE
Files should be written out in a streaming fashion

### ISSUE THREAD

**Issue by mstange** [mstange/symsrv#5]
At the moment we download the entire file into memory, and then write it out. We can write out the individual chunks as they come in.

**Comment by DrChat** [comment]
This is amazing - thanks for doing this! Will look into integrating your work in the future :)

**Comment by mstange** [comment]
Great! There's a small problem with the streaming download at the moment, which I intend to fix before the next symsrv release: The partial files which are created during download currently have the final filename during the download, so if you check the file before it's fully downloaded you might accidentally try to load an incomplete file. I want to fix it so that we use filenames such as `pdbname.pdb.part` during the download and then rename once the download is completed, or delete if the download fails halfway through.

I also have a WIP branch which allows reporting progress percentage through a delegate trait object.
